// THE GATHERING (S3 remake) — the ecosystem as a convergence in DEPTH.
//
// The Problem leaves the liquid fractured and dispersed: the client's tools,
// each working alone. This chapter is the answer, and the answer is not a
// diagram of boxes joined by lines — it is those same fragments being drawn
// forward out of the dark until they are one body.
//
// Depth carries the argument. Every capability starts FAR (z → 1: dim, small,
// absorbed toward the sub-surface grade the shader already applies) and
// scattered across the full bleed. Scroll pulls each one FORWARD (z → 0) and
// INWARD at the same time, so a scattered, distant, half-lit field resolves
// into a near, bright, single mass. Nothing is drawn between them; they simply
// stop being separate — which is the claim the chapter makes in words.
//
// The ten capabilities arrive in the three authored systems, so the reader gets
// three beats rather than ten. Each system is a LOBE around the mark, not a
// slot on a circle: a compass ring reads as a diagram, and three organic
// clusters read as anatomy.
//
// Single source of truth for the geometry: the
// canvas masses (site scene) and the DOM labels evaluate the SAME functions, so
// the liquid and the type can never drift apart. uv space throughout (y up, x
// centred on 0.5 spanning the aspect).

import { smooth01, hash } from "./phys.mjs";

export const GATHER_N = 10;

/**
 * The three organ systems, as indices into the authored `ecosystem.nodes`.
 * This grouping is the business truth and is carried over unchanged from the
 * circuit: identity = brand/content/site, growth = traffic/service/CRM,
 * operation = AI/automation/internal systems/dashboards.
 */
export const GATHER_SYSTEMS = [
  { id: "identity", nodes: [0, 9, 1] },
  { id: "growth", nodes: [2, 8, 3] },
  { id: "operation", nodes: [4, 5, 7, 6] },
];

/** node index → { system index, position within the system } */
export const SYS_OF_NODE = [];
GATHER_SYSTEMS.forEach((sys, si) =>
  sys.nodes.forEach((n, wi) => (SYS_OF_NODE[n] = { si, wi })),
);

// ── THE FIELD ────────────────────────────────────────────────────────────────
// The gathering is not centred on the stage any more: it owns a FIELD, and the
// chapter's type owns the column beside it.
//
// Everything used to be centred on 0.5 and spread to the frame edges, so the
// ten names had nowhere to live except on top of the liquid. Whatever the
// placement rule was — at the mass, on a grid, nudged to dodge a neighbour —
// type over a moving body reads as loose, because it is: there is no edge in
// the composition for it to be measured against. Giving the liquid a field and
// the type a column is what makes both read as PLACED, and it costs the liquid
// nothing — a convergence is just as legible off-centre.
//
// Expressed in PAGE FRACTION (0 = left edge, 1 = right edge) and converted to
// uv here, because the column it has to clear is a CSS width, not a uv one.
// cx/half are tuned against TWO edges, not one: the column's right edge on the
// left (the field starts ~300px clear of it, because free liquid drifts and a
// tight gap puts beads on the type) and the chapter-index rail on the right.
const FIELD_WIDE = { cx: 0.71, half: 0.25 }; // column left, liquid right
const FIELD_NARROW = { cx: 0.5, half: 0.42 }; // no column: the field is centred

/**
 * The viewport width at which the type column exists.
 *
 * THIS MUST MATCH the `min-width: 1024px` guard on `.gather-col` in
 * globals.css, and the split has to be decided on WIDTH for that reason — the
 * column is a CSS breakpoint, not an aspect ratio. Deciding it on aspect
 * instead put the two out of step in both directions: a 900x620 stage has an
 * aspect of 1.45, so the liquid moved right to clear a column that was not
 * rendered at all, and a 1024x768 one has 1.33, so the liquid centred itself
 * underneath a column that was. Both are the same bug — two breakpoints
 * describing one composition.
 */
export const FIELD_MIN_W = 1024;

/** The gathering's field for a stage of width `vw`, in page fractions. */
export function gatherField(vw) {
  return vw >= FIELD_MIN_W ? FIELD_WIDE : FIELD_NARROW;
}

/**
 * uv x-offset of the field's centre from the stage centre. The scene applies
 * this to the mark's own footprint so the body fuses INSIDE the field rather
 * than sliding back to the middle of the stage at the last moment.
 */
export function gatherOffsetX(aspect, vw) {
  return (gatherField(vw).cx - 0.5) * aspect;
}

/**
 * The field's left edge in uv — the line the chapter's liquid does not cross.
 *
 * The dispersed scatter is generated by the shared `wideScatter`, whose own
 * clamp is measured from the STAGE centre: it keeps liquid inside the frame,
 * which is the right guarantee when the composition is centred and the wrong
 * one as soon as it is not. Without a field edge, targets on the left tail of
 * the scatter land under the column and free physics carries a few further
 * still, which puts beads on the type — the exact defect the split exists to
 * remove, reintroduced through the back door.
 *
 * Clamping the TARGET (not the droplet) is deliberate: the liquid stays fully
 * free, so it still drifts, merges and answers the cursor. It simply has
 * nowhere to be pulled toward on the type's side of the stage.
 */
export function gatherLeftEdge(aspect, vw) {
  const f = gatherField(vw);
  return 0.5 + (f.cx - f.half - 0.5) * aspect;
}

// ── the three lobes ──────────────────────────────────────────────────────────
// Direction and reach of each system's cluster from the field centre, in UNIT
// field space (±1 = the field's own edge) rather than in raw uv. Deliberately
// uneven: equal thirds would rebuild the compass this design exists to avoid.
// Unit space is what keeps the constellation inside the field at every aspect —
// the old raw-uv reach overflowed the right edge as soon as the field moved off
// the stage centre.
export const LOBES = [
  { dx: -0.54, dy: 0.44, spread: 0.1 }, // identity — upper left of the field
  { dx: 0.6, dy: 0.04, spread: 0.11 }, // growth — right, the widest reach
  { dx: -0.08, dy: -0.56, spread: 0.12 }, // operation — below, the broadest base
];

/**
 * A lobe's BEARING from the field centre at a given aspect, in radians.
 *
 * gatherAnchor maps a lobe's unit direction through two different scales — the
 * field half-width on x (aspect-dependent) and a fixed 0.32 on y — so the
 * direction a reader actually sees is not atan2(dy, dx). THE CONFLUENCE
 * (confluence.mjs) has to stand where the lobes have been arriving, so it reads
 * the bearing through the same mapping rather than re-deriving it.
 */
export function lobeBearing(si, aspect, half = FIELD_WIDE.half) {
  const l = LOBES[si];
  return Math.atan2(l.dy * 0.32, l.dx * half * aspect);
}

// Per-capability offset inside its lobe. Authored rather than hashed: these are
// read as a constellation, so the clusters need to be legible, not random.
const IN_LOBE = [
  [-0.42, 0.5],
  [0.55, 0.16],
  [-0.2, -0.55],
  [0.5, -0.42],
];

const CY = 0.5;

/**
 * Where capability `n` rests once it has been gathered (uv, y up).
 * This is the NEAR anchor — the position the mass holds while the system is
 * assembled and its row is lit in the column.
 */
export function gatherAnchor(n, aspect, vw) {
  const { si, wi } = SYS_OF_NODE[n];
  const lobe = LOBES[si];
  const off = IN_LOBE[wi % IN_LOBE.length];
  const f = gatherField(vw);
  const halfX = f.half * aspect; // page half-width → uv
  const cx = 0.5 + gatherOffsetX(aspect, vw);
  return {
    x: cx + (lobe.dx + off[0] * lobe.spread * 3.1) * halfX,
    y: CY + (lobe.dy + off[1] * lobe.spread * 2.0) * 0.32,
  };
}

/**
 * Ignition timing for capability `n` on the gather clock. The systems arrive in
 * order and overlap slightly — a hard sequence would read as a playlist, and
 * the overlap is what makes it look like one process with three phases.
 */
export function gatherTiming(n) {
  const { si, wi } = SYS_OF_NODE[n];
  return { d: 0.06 + si * 0.235 + wi * 0.045, w: 0.2 };
}

/** System `si`'s own envelope — drives the reach markers in the DOM. */
export function systemTiming(si) {
  return { d: 0.06 + si * 0.235, w: 0.26 };
}

export const env = (p, t) => smooth01((p - t.d) / t.w);

/**
 * Depth for capability `n` at gather progress `p`.
 *
 * 1 = far (the shader's depth grade dims it toward sub-surface), 0 = near. The
 * curve leads the positional arrival slightly: a mass brightens as it commits
 * to coming forward, before it has finished travelling. That lead is what makes
 * the convergence feel like it is being pulled rather than played back.
 */
export function gatherDepth(n, p) {
  const t = gatherTiming(n);
  return 1 - env(p, { d: t.d, w: t.w * 0.78 });
}

/**
 * The closing fuse: once every system has landed, the three lobes are drawn
 * into the single body. Pure function of p (scrub-safe, reversible), and 0
 * until the last capability has arrived so nothing collapses early.
 */
export function fuse(p) {
  return smooth01((p - 0.82) / 0.18);
}

/**
 * A capability's own arrival pulse — a short swell as its mass lands, used to
 * brighten both the bead and its label at the same instant. Peaks at the
 * moment of arrival and decays; never a step.
 */
export function arrivalPulse(n, p) {
  const t = gatherTiming(n);
  const u = (p - t.d) / t.w;
  if (u <= 0 || u >= 1.6) return 0;
  return Math.sin(Math.PI * Math.min(u / 1.6, 1)) ** 2;
}

// ── droplet allocation (the site scene, i < 40) ──────────────────────────────
// Each capability owns a small FAMILY of droplets rather than one bead: a lone
// disc per capability is a bullet point, while three or four that hold together
// under cohesion and merge on arrival read as a body of liquid. The families
// share a cluster id so fluid-core's cohesion keeps them together in flight.
export const GATHER_FAMILY = 3; // droplets per capability (10 × 3 = 30)
export const GATHER_DROPS = GATHER_N * GATHER_FAMILY;

/** droplet i → capability index, or -1 if it is not part of the gathering. */
export const NODE_OF = (i) => (i < GATHER_DROPS ? Math.floor(i / GATHER_FAMILY) : -1);

/**
 * Offset of droplet `i` inside its capability's family (uv). Hash-seeded so the
 * families are irregular, scaled so they read as one mass rather than a row.
 */
export function familyOffset(i) {
  const k = i % GATHER_FAMILY;
  const a = hash(i, 61) * Math.PI * 2;
  const d = 0.006 + 0.013 * hash(i, 62);
  return { x: Math.cos(a) * d, y: Math.sin(a) * d * 0.8, lead: k / GATHER_FAMILY };
}

/** Visible radius of a gathered droplet: far liquid is small, near liquid full. */
export function gatherRadius(i, depth, pulse) {
  const base = 0.0125 + 0.0075 * hash(i, 63);
  // Perspective, not just dimming — the shader's depth grade handles light and
  // this handles size, so a far mass is genuinely a smaller thing further away.
  //
  // The old floor was 0.42, which is not a distance: a mass at the back of the
  // field rendered a bit over half the size of one at the front, and since the
  // approach is also the only thing that changes across the runway, two stops a
  // full viewport apart looked identical. 0.16 is a real horizon — the same
  // capability reads as a speck arriving out of the dark and then as a body.
  return base * (0.16 + 0.84 * (1 - depth)) * (1 + 0.34 * pulse);
}

/**
 * THE RECEDE. How far the not-yet-gathered field has fallen back into the dark
 * at travel `tr` (the runway's own approach, 0 → 1 as the chapter takes over).
 *
 * The Problem hands over a field of near, full-size fragments. If they simply
 * wait there at that size until their own envelope opens, the chapter's first
 * half is a still image — which is exactly what it was: the scatter held the
 * mark's footprint radius until `e` opened, so nothing about a droplet changed
 * for one to two full viewports of scroll.
 *
 * Letting them fall away first is both the fix and the better story: the
 * fragments recede, and the recovery is then something the scroll earns back.
 * `1` = untouched (as The Problem left them), `0` = fully receded.
 */
export function recede(tr) {
  return 1 - 0.45 * smooth01(tr);
}
